name: tomcat_deploy
on:
- push
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:

    - name: checkout the code
      uses: actions/checkout@v6

    - name: listing the code
      run: ls
    
    - name: installing java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: building the code
      run: |
        mvn clean package
    
    - name: listing the code
      run: ls -lR

    - name: upload the artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ./target/*.war

  deploy_job:
    needs: 
    - build_job
    runs-on: ubuntu-latest
    steps:

    - name: downloding the artifact
      uses: actions/download-artifact@v8
      with:
        name: my-artifact
        path: /opt/target/
    
    - name: Listing the artifact
      run: ls -l /opt/target

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload to S3
      run: |
         aws s3 cp /opt/target/* s3://${{ vars.BUCKET_NAME }}/app
    
    - uses: joutvhu/download-s3@v1
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws_region: us-east-1
        aws_bucket: ${{ vars.BUCKET_NAME }}
        source: '/app/*.war'
        target: '/opt'
    
    - name: listing the war file
      run: ls -l /opt

    - name: deploying to tomcat
      run: |
        curl -u admin:admin --upload-file /opt/*.war "http://100.55.169.24:8080/manager/text/deploy?path=/myapp&update=true"